// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Adding3PropertiesToMoviesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding3PropertiesToMoviesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201707242305469_Adding3PropertiesToMoviesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
